---
# Source: mongodb-enterprise-operator/templates/crds.yaml


---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbstandalones.mongodb.com
spec:
  group: mongodb.com
  version: v1
  scope: Namespaced
  names:
    kind: MongoDbStandalone
    plural: mongodbstandalones
    shortNames:
    - mst
    singular: mongodbstandalone
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            spec:
              properties:
                credentials:
                  type: string
                project:
                  type: string
                version:
                  type: string
                logLevel:
                  type: string
                  enum:
                  - DEBUG
                  - INFO
                  - WARN
                  - ERROR
                  - FATAL
          required:
          - credentials
          - project
          - version

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbreplicasets.mongodb.com
spec:
  group: mongodb.com
  version: v1
  scope: Namespaced
  names:
    kind: MongoDbReplicaSet
    singular: mongodbreplicaset
    plural: mongodbreplicasets
    shortNames:
    - mrs
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            members:
              maximum: 50
              minimum: 1
              type: integer
            spec:
              properties:
                credentials:
                  type: string
                project:
                  type: string
                version:
                  type: string
                logLevel:
                  type: string
                  enum:
                  - DEBUG
                  - INFO
                  - WARN
                  - ERROR
                  - FATAL
          required:
          - credentials
          - project
          - version
          - members

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbshardedclusters.mongodb.com
spec:
  group: mongodb.com
  version: v1
  scope: Namespaced
  names:
    kind: MongoDbShardedCluster
    plural: mongodbshardedclusters
    shortNames:
    - msc
    singular: mongodbshardedcluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            configServerCount:
              maximum: 50
              minimum: 1
              type: integer
            mongodsPerShardCount:
              maximum: 50
              minimum: 1
              type: integer
            mongosCount:
              minimum: 1
              type: integer
            shardCount:
              minimum: 1
              type: integer
            spec:
              properties:
                credentials:
                  type: string
                project:
                  type: string
                version:
                  type: string
                logLevel:
                  type: string
                  enum:
                  - DEBUG
                  - INFO
                  - WARN
                  - ERROR
                  - FATAL
          required:
          - credentials
          - project
          - version
          - shardCount
          - mongodsPerShardCount
          - mongosCount
          - configServerCount


