---
# Source: mongodb-enterprise-operator/templates/roles.yaml
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-operator

rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["*"]
- apiGroups:
  - mongodb.com
  resources:
  - "*"
  verbs:
  - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-operator

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-enterprise-operator
subjects:
- kind: ServiceAccount
  name: mongodb-enterprise-operator

---
# Source: mongodb-enterprise-operator/templates/serviceaccount.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-operator

---
# Source: mongodb-enterprise-operator/templates/operator.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-enterprise-operator

spec:
  replicas: 1
  selector:
      matchLabels:
        app: mongodb-enterprise-operator
  template:
    metadata:
      labels:
        app: mongodb-enterprise-operator
    spec:
      serviceAccountName: mongodb-enterprise-operator
      containers:
      - name: mongodb-enterprise-operator
        image: registry.connect.redhat.com/mongodb/enterprise-operator
        imagePullPolicy: Always
        env:
        - name: OPERATOR_ENV
          value: prod
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MANAGED_SECURITY_CONTEXT
          value: 'true'
        - name: MONGODB_ENTERPRISE_DATABASE_IMAGE
          value: registry.connect.redhat.com/mongodb/enterprise-database
        - name: IMAGE_PULL_POLICY
          value: Always
