project_name: kubectl-mongodb

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64

    hooks:
      # This will notarize Apple binaries and replace goreleaser bins with the notarized ones
      post:
        - cmd: ./kubectl_mac_notarize.sh
          output: true

archives:
  - format: tar.gz
    name_template: "kubectl-mongodb_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true

release:
  prerelease: auto
  draft: true
  name_template: "MongoDB Enterprise CLI {{ .Version  }}"

git:
  tag_sort: -version:creatordate
