project_name: kubectl-mongodb

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    hooks:
      post:
        - cmd: ./sign.sh {{ .Path }}
          env:
            - GRS_USERNAME={{ .Env.GRS_USERNAME }}
            - GRS_PASSWORD={{ .Env.GRS_PASSWORD }}
            - PKCS11_URI={{ .Env.PKCS11_URI }}
            - ARTIFACTORY_USERNAME=mongodb-enterprise-kubernetes-operator
            - ARTIFACTORY_PASSWORD={{ .Env.ARTIFACTORY_PASSWORD }}
        - cmd: ./verify.sh {{ .Path }} && echo "VERIFIED OK"
        - cmd: ./kubectl_mac_notarize.sh
          output: true

archives:
  - format: tar.gz
    name_template: "kubectl-mongodb_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true

release:
  prerelease: auto
  draft: true
  name_template: "MongoDB Enterprise CLI {{ .Version  }}"
  extra_files:
    - glob: dist/*.sig

git:
  tag_sort: -version:creatordate
