project_name: kubectl-mongodb

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    hooks:
      # This will notarize Apple binaries and replace goreleaser bins with the notarized ones
      post:
        - cmd: ./kubectl_mac_notarize.sh
          output: true
        - cmd: ./sign.sh {{ .Path }}
          env:
            - GRS_USERNAME={{ .Env.GRS_USERNAME }}
            - GRS_PASSWORD={{ .Env.GRS_PASSWORD }}
            - PKCS11_URI={{ .Env.PKCS11_URI }}
            - ARTIFACTORY_URL={{ .Env.ARTIFACTORY_URL }}
            - SIGNING_IMAGE_URI={{ .Env.SIGNING_IMAGE_URI }}
            - ARTIFACTORY_USERNAME=mongodb-enterprise-kubernetes-operator
            - ARTIFACTORY_PASSWORD={{ .Env.ARTIFACTORY_PASSWORD }}
        - cmd: ./verify.sh {{ .Path }} && echo "VERIFIED OK"
        
archives:
  - format: tar.gz
    name_template: "kubectl-mongodb_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      # Include signature files in each archive along with the binary, strip_parent avoid nested folders
      - src: "./dist/kubectl-mongodb_{{ .Os }}_{{ .Arch }}*{{ .Amd64 }}/kubectl-mongodb.sig"
        strip_parent: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true

release:
  prerelease: auto
  draft: true
  name_template: "MongoDB Enterprise Kubernetes Operator {{ .Version  }}"

git:
  tag_sort: -version:creatordate
