---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager-scram
spec:
  replicas: 1
  version: 5.0.5
  adminCredentials: ops-manager-admin-secret

  # the application database backing Ops Manager. Replica Set is the only supported type
  # Application database has the SCRAM-SHA authentication mode always enabled
  applicationDatabase:
    version: "4.4.11-ent"
    members: 3
    podSpec:
      cpu: '0.25'
    # optional. Specifies the secret which contains the password used to connect to the database
    # If not specified - the Operator will generate a random password
    passwordSecretKeyRef:
      name: my-password-secret
      # optional, default is "password"
      key: password-key
