apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager-localmode
spec:
  replicas: 2
  version: 5.0.5
  adminCredentials: ops-manager-admin-secret
  configuration:
    # this enables local mode in Ops Manager
    automation.versions.source: local

  statefulSet:
    spec:
      # the Persistent Volume Claim will be created for each Ops Manager Pod
      volumeClaimTemplates:
        - metadata:
            name: mongodb-versions
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 20G
      template:
        spec:
          containers:
            - name: mongodb-ops-manager
              volumeMounts:
                - name: mongodb-versions
                  # this is the directory in each Pod where all MongoDB
                  # archives must be put
                  mountPath: /mongodb-ops-manager/mongodb-releases


  backup:
    enabled: false

  applicationDatabase:
    version: "4.4.11-ent"
    members: 3
