{
 "title": "MongoDB Enterprise Dashboard",
 "tags": [ "MongoDB Enterprise" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_connections_available,cl_name)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime (minutes)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_uptimeMillis{cl_name=\"mfst-db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connections_available{cl_name=\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mongodb_connections_active{cl_name=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mongo Pods Memory Usage in GB / Total Available on Cluster",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$cluster.*\", container=~\"mongodb-.*\"})",
     "legendFormat": "Mongo Pod Usage"
    },
    {
     "expr": ":node_memory_MemAvailable_bytes:sum",
     "legendFormat": "Total Available"
    }
   ]
  },
  {
   "title": "Mongo Pods CPU Usage / Total Available on Cluster",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$cluster.*\", image!~\"sha.*\", container=~\"mongo.*\"}[5m]))",
     "legendFormat": "Mongo Pod Usage"
    },
    { "expr": "cluster:node_cpu:sum_rate5m", "legendFormat": "Total Available" }
   ]
  },
  {
   "title": "Catalog Stats",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_catalogStats_collections{pod=~\"$cluster.*\"})",
     "legendFormat": "Collections"
    },
    {
     "expr": "max(mongodb_catalogStats_capped{pod=~\"$cluster.*\"})",
     "legendFormat": "Capped Collections"
    },
    {
     "expr": "max(mongodb_catalogStats_timeseries{pod=~\"$cluster.*\"})",
     "legendFormat": "Timeseries"
    },
    {
     "expr": "max(mongodb_catalogStats_views{pod=~\"$cluster.*\"})",
     "legendFormat": "Views"
    }
   ]
  },
  {
   "title": "Global Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(mongodb_globalLock_activeClients_total{pod=~\"$cluster.*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(mongodb_globalLock_activeClients_readers{pod=~\"$cluster.*\"})",
     "legendFormat": "Readers"
    },
    {
     "expr": "sum(mongodb_globalLock_activeClients_writers{pod=~\"$cluster.*\"})",
     "legendFormat": "Writers"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(mongodb_metrics_cursor_open_total{pod=~\"$cluster.*\"})",
     "legendFormat": "{{pod}} Open"
    },
    {
     "expr": "sum(mongodb_metrics_cursor_open_noTimeout{pod=~\"$cluster.*\"})",
     "legendFormat": "{{pod}} Open No Timeout"
    },
    {
     "expr": "mongodb_metrics_cursor_timed_out{pod=~\"$cluster.*\"}",
     "legendFormat": "{{pod}} Timed Out"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (cl_name) (rate(mongodb_metrics_document_inserted{pod=~\"$cluster.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} Inserted"
    },
    {
     "expr": "sum by (cl_name) (rate(mongodb_metrics_document_returned{pod=~\"$cluster.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} Returned"
    },
    {
     "expr": "sum by (cl_name) (rate(mongodb_metrics_document_deleted{pod=~\"$cluster.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} Deleted"
    },
    {
     "expr": "sum by (cl_name) (rate(mongodb_metrics_document_updated{pod=~\"$cluster.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} Updated"
    }
   ]
  },
  {
   "title": "Replication Network Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_metrics_repl_network_bytes{pod=~\"$cluster.*\"})",
     "legendFormat": "Total Usage"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_metrics_repl_network_ops{pod=~\"$cluster.*\"})",
     "legendFormat": "Total Usage"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (cl_name) (rate(mongodb_network_bytesIn{pod=~\"$cluster.*\"}[1m]))",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "- sum by (cl_name) (rate(mongodb_network_bytesOut{pod=~\"$cluster.*\"}[1m]))",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (cl_name) (rate(mongodb_opLatencies_reads_latency{cl_name=\"$cluster\"}[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum by (cl_name) (rate(mongodb_opLatencies_writes_latency{cl_name=\"$cluster\"}[1m]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum by (cl_name) (rate(mongodb_opLatencies_commands_latency{pod=~\"$cluster.*\"}[1m]))",
     "legendFormat": "Commands"
    },
    {
     "expr": "sum by (cl_name) (rate(mongodb_opLatencies_transactions_latency{pod=~\"$cluster.*\"}[1m]))",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cl_name) (rate(mongodb_opLatencies_reads_ops{pod=~\"$cluster.*\"}[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum by (cl_name) (rate(mongodb_opLatencies_writes_ops{pod=~\"$cluster.*\"}[1m]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum by (cl_name) (rate(mongodb_opLatencies_commands_ops{pod=~\"$cluster.*\"}[1m]))",
     "legendFormat": "Commands"
    },
    {
     "expr": "sum by (cl_name) (rate(mongodb_opLatencies_transactions_ops{pod=~\"$cluster.*\"}[1m]))",
     "legendFormat": "Transactions"
    }
   ]
  }
 ]
}