#!/usr/bin/env bash

SUDO=sudo

# jq, yq
# echo "Installing jq and yq"
# curl -Lo jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
# chmod +x jq
# $SUDO mv jq /usr/local/bin/
# curl -Lo yq https://github.com/mikefarah/yq/releases/download/2.2.1/yq_linux_amd64
# chmod +x yq
# $SUDO mv yq /usr/local/bin/
# # operator-courier
# echo "Installing operator-courier"
# python3 -m pip install operator-courier
# # SDK
# echo "Installing operator-sdk"
# SDK_VER="v0.6.0"
# curl -Lo operator-sdk "https://github.com/operator-framework/operator-sdk/releases/download/${SDK_VER}/operator-sdk-${SDK_VER}-x86_64-linux-gnu"
# chmod +x operator-sdk
# $SUDO mv operator-sdk /usr/local/bin/
# # helm
# echo "Installing helm"
# curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
# kubectl
echo "Installing kubectl"
KUBE_VER="v1.13.0"
curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/${KUBE_VER}/bin/linux/amd64/kubectl"
chmod +x kubectl
$SUDO mv kubectl /usr/local/bin/

# minikube and crictl dependency
echo "Installing minikube and crictl"
curl -Lo crictl.tar.gz "https://github.com/kubernetes-sigs/cri-tools/releases/download/${KUBE_VER}/crictl-${KUBE_VER}-linux-amd64.tar.gz"
tar -zxvf crictl.tar.gz
chmod +x crictl
$SUDO mv crictl /usr/local/bin/
rm crictl.tar.gz
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
chmod +x minikube
$SUDO mv minikube /usr/local/bin/

# kind
echo "Installing kind"
curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.5.1/kind-linux-amd64
chmod +x kind
$SUDO mv kind /usr/local/bin/
