name: mongodb-enterprise-operator
description: MongoDB Kubernetes Enterprise Operator
version: 1.2.4
kubeVersion: '>=1.11'
keywords:
- mongodb
- database
- nosql
home: https://github.com/mongodb/mongodb-enterprise-kubernetes
maintainers:
- name: Cloud Team
