---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: my-ldap-user
spec:
  username: my-ldap-user
  db: $external
  mongodbResourceRef:
    name: my-ldap-enabled-sharded-cluster # The name of the MongoDB resource this user will be added to
  roles:
    - db: admin
      name: clusterAdmin
    - db: admin
      name: userAdminAnyDatabase
    - db: admin
      name: readWrite
