{{ if eq .Values.createCrds true}}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodb.mongodb.com
spec:
  group: mongodb.com
  version: v1
  scope: Namespaced
  names:
    kind: MongoDB
    plural: mongodb
    shortNames:
    - mdb
    singular: mongodb
  additionalPrinterColumns:
    - name: Type
      type: string
      description: "The type of MongoDB deployment. One of 'ReplicaSet', 'ShardedCluster' and 'Standalone'."
      JSONPath: .spec.type
    - name: State
      type: string
      description: The current state of the MongoDB deployment.
      JSONPath: .status.phase
    - name: Version
      type: string
      description: The version of MongoDB.
      JSONPath: .spec.version
    - name: Age
      type: date
      description: The time since the MongoDB resource was created.
      JSONPath: .metadata.creationTimestamp
  validation: # there are 3 possible schemas, ReplicaSet, ShardedCluster and Standalone
    openAPIV3Schema:
      oneOf:
      - properties: # Standalone schema
          spec:
            properties:
              credentials:
                type: string
              project:
                type: string
                description: "DEPRECATED The name of a configMap in the same namespace"
              opsManager:
                properties:
                  configMapRef:
                    properties:
                      name:
                        type: string
              cloudManager:
                properties:
                  configMapRef:
                    properties:
                      name:
                        type: string
              version:
                type: string
                pattern: "^[0-9]+.[0-9]+.[0-9]+(-.+)?$"
              logLevel:
                type: string
                enum: ["DEBUG", "INFO", "WARN", "ERROR", "FATAL"]
              type:
                type: string
                pattern: "^Standalone$"
              security:
                type: object
                properties:
                  authentication:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                      modes:
                        type: array
                        items:
                          type: string
                          enum: ["SCRAM", "X509"]
                      ignoreUnknownUsers:
                        type: boolean
                  tls:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                      ca:
                        type: string
                      additionalCertificateDomains:
                        type: array
                        items:
                          type: string
              connectivity:
                not:
                  required: ["replicaSetHorizons"]
              additionalMongodConfig:
                properties:
                  net:
                    properties:
                      ssl:
                        properties:
                          mode:
                            type: string
                            enum: ["disabled", "allowSSL", "preferSSL", "requireSSL", "allowTLS", "preferTLS", "requireTLS"]
              exposedExternally:
                type: boolean
            oneOf:
              - required: [project]
              - required: [opsManager]
              - required: [cloudManager]
            required:
            - credentials
            - version
            - type
      - properties: # ReplicaSet schema
          spec:
            properties:
              members:
                maximum: 50
                minimum: 1
                type: integer
              credentials:
                type: string
              project:
                type: string
                description: "DEPRECATED The name of a configMap in the same namespace"
              opsManager:
                properties:
                  configMapRef:
                    properties:
                      name:
                        type: string
              cloudManager:
                properties:
                  configMapRef:
                    properties:
                      name:
                        type: string
              version:
                type: string
                pattern: "^[0-9]+.[0-9]+.[0-9]+(-.+)?$"
              logLevel:
                type: string
                enum: ["DEBUG", "INFO", "WARN", "ERROR", "FATAL"]
              type:
                type: string
                pattern: "^ReplicaSet$"
              security:
                type: object
                properties:
                  authentication:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                      modes:
                        type: array
                        items:
                          type: string
                          enum: ["SCRAM", "X509"]
                      internalCluster:
                        type: string
                        enum: ["X509"]
                      ignoreUnknownUsers:
                        type: boolean
                  tls:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                      ca:
                        type: string
                      additionalCertificateDomains:
                        type: array
                        items:
                          type: string
                  clusterAuthenticationMode:
                    # Warning: please refer to the documentation before enabling X509 in your MongoDB resource.
                    # https://docs.mongodb.com/kubernetes-operator/
                    type: string
                    enum: ["x509"]
              connectivity:
                properties:
                  replicaSetHorizons:
                    type: array
                    items:
                      type: object
                      additionalProperties:
                        type: string
              additionalMongodConfig:
                properties:
                  net:
                    properties:
                      ssl:
                        properties:
                          mode:
                            type: string
                            enum: ["disabled", "allowSSL", "preferSSL", "requireSSL", "allowTLS", "preferTLS", "requireTLS"]
              exposedExternally:
                type: boolean
            oneOf:
              - required: [project]
              - required: [opsManager]
              - required: [cloudManager]
            required:
            - credentials
            - version
            - type
            - members
            # TODO: add validation for OpsManager or Cloud Manager being required
      - properties:
          spec:
            properties: # ShardedCluster schema
              configServerCount:
                maximum: 50
                minimum: 1
                type: integer
              mongodsPerShardCount:
                maximum: 50
                minimum: 1
                type: integer
              mongosCount:
                minimum: 1
                type: integer
              shardCount:
                minimum: 1
                type: integer
              credentials:
                type: string
              project:
                type: string
                description: "DEPRECATED The name of a configMap in the same namespace"
              opsManager:
                properties:
                  configMapRef:
                    properties:
                      name:
                        type: string
              cloudManager:
                properties:
                  configMapRef:
                    properties:
                      name:
                        type: string
              version:
                type: string
                pattern: "^[0-9]+.[0-9]+.[0-9]+(-.+)?$"
              logLevel:
                type: string
                enum: ["DEBUG", "INFO", "WARN", "ERROR", "FATAL"]
              type:
                type: string
                pattern: "^ShardedCluster$"
              security:
                type: object
                properties:
                  authentication:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                      modes:
                        type: array
                        items:
                          type: string
                          enum: ["SCRAM", "X509"]
                      internalCluster:
                        type: string
                        enum: ["X509"]
                      ignoreUnknownUsers:
                        type: boolean
                  tls:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                      ca:
                        type: string
                      additionalCertificateDomains:
                        type: array
                        items:
                          type: string
                  clusterAuthenticationMode:
                    # Warning: please refer to the documentation before enabling X509 in your MongoDB resource.
                    # https://docs.mongodb.com/kubernetes-operator/
                    type: string
                    enum: ["x509"]
              connectivity:
                not:
                  required: ["replicaSetHorizons"]
              additionalMongodConfig:
                properties:
                  net:
                    properties:
                      ssl:
                        properties:
                          mode:
                            type: string
                            enum: ["disabled", "allowSSL", "preferSSL", "requireSSL", "allowTLS", "preferTLS", "requireTLS"]
              exposedExternally:
                type: boolean
            oneOf:
              - required: [project]
              - required: [opsManager]
              - required: [cloudManager]
            required:
            - credentials
            - version
            - type
            - shardCount
            - mongodsPerShardCount
            - mongosCount
            - configServerCount
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbusers.mongodb.com
spec:
  group: mongodb.com
  version: v1
  scope: Namespaced
  names:
    kind: MongoDBUser
    plural: mongodbusers
    shortNames:
    - mdbu
    singular: mongodbuser
  additionalPrinterColumns:
    - name: State
      type: string
      description: The current state of the MongoDB User
      JSONPath: .status.phase
    - name: Age
      type: date
      description: The time since the MongoDB User resource was created
      JSONPath: .metadata.creationTimestamp
  validation:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              username:
                type: string
                description: "The username of the user"
              db:
                type: string
                description: "The database the user is stored in"
              project:
                type: string
                description: "The project the user belongs to"
              passwordSecretKeyRef:
                type: object
                properties:
                  name:
                    type: string
                  key:
                    type: string
                description: "DEPRECATED The project the user belongs to"
              mongodbResourceRef:
                properties:
                  name:
                    type: string
                    description: "The name of a MongoDB resource in the same namespace"
              roles:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: "The name of the role"
                    db:
                      type: string
                      description: "The db the role can act on"
                    passwordSecretKeyRef:
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                  required:
                    - name
                    - db
            required:
              - username
              - db
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: opsmanagers.mongodb.com
spec:
  group: mongodb.com
  version: v1
  scope: Namespaced
  names:
    kind: MongoDBOpsManager
    plural: opsmanagers
    shortNames:
    - om
    singular: opsmanager
  additionalPrinterColumns:
    - name: Replicas
      type: integer
      description: The number of replicas of MongoDBOpsManager.
      JSONPath: .spec.replicas
    - name: Version
      type: string
      description: The version of MongoDBOpsManager.
      JSONPath: .spec.version
    - name: Version (DB)
      type: string
      description: The version of Application Database  .
      JSONPath: .spec.applicationDatabase.version
    - name: State
      type: string
      description: The current state of the MongoDBOpsManager.
      JSONPath: .status.opsManager.phase
    - name: State (DB)
      type: string
      description: The current state of the MongoDBOpsManager Application Database.
      JSONPath: .status.applicationDatabase.phase
    - name: Age
      type: date
      description: The time since the MongoDBOpsManager resource was created.
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            version:
              type: string
            replicas:
              minimum: 1
              type: integer
            externalConnectivity:
              type: object
              properties:
                type:
                  type: string
                  enum: ["LoadBalancer", "NodePort"]
                port:
                  type: integer
                loadBalancerIP:
                  type: string
                externalTrafficPolicy:
                  type: string
                  enum: ["Cluster", "Local"]
                annotations:
                  type: object
              required:
                - type
            backup:
              type: object
              properties:
                enabled:
                  type: boolean
                headDB:
                  type: object
                  properties:
                    storage:
                      type: string
                    storageClass:
                      type: string
                opLogStores:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      mongodbResourceRef:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                          - name
                      mongodbUserRef:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                            - name
                    required:
                      - name
                      - mongodbResourceRef
                s3Stores:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                    mongodbResourceRef:
                      type: object
                      properties:
                        name:
                          type: string
                      required:
                        - name
                    mongodbUserRef:
                      type: object
                      properties:
                        name:
                          type: string
                      required:
                        - name
                    pathStyleAccessEnabled:
                      type: boolean
                    s3BucketEndpoint:
                      type: string
                    s3BucketName:
                      type: string
                    s3SecretRef:
                      type: object
                      properties:
                        name: string
                    required:
                      - name
                      - mongodbResourceRef
                      - pathStyleAccessEnabled
                      - s3BucketEndpoint
                      - s3BucketName
                      - s3SecretRef

              required:
                - enabled

            applicationDatabase:
              type: object
              properties:
                passwordSecretKeyRef:
                  type: object
                  properties:
                    name:
                      type: string
                    key:
                      type: string
                  required:
                    - name
                members:
                  maximum: 50
                  minimum: 3
                  type: integer
                version:
                  type: string
                  pattern: "^[0-9]+.[0-9]+.[0-9]+(-.+)?$"
                logLevel:
                  type: string
                  enum: ["DEBUG", "INFO", "WARN", "ERROR", "FATAL"]
                exposedExternally:
                  type: boolean
              required:
                - version
                - members
          required:
            - version
            - applicationDatabase

{{end}}
