name: Release multicluster-cli binary
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          # When running verify.sh hooks in parallel, Rekor fails with: resource temporarily unavailable
          args: release --rm-dist --timeout 300 --parallelism 1
          workdir: ./tools/multicluster
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
          PKCS11_URI: ${{ secrets.PKCS11_URI }}
          GRS_USERNAME: ${{ secrets.GRS_USERNAME }}
          GRS_PASSWORD: ${{ secrets.GRS_PASSWORD }}
          ARTIFACTORY_PASSWORD: {{ secrets.ARTIFACTORY_PASSWORD }}
